#========================================
# General settings
#========================================
integration:
  byggr:
    connect-timeout-in-seconds: 10
    read-timeout-in-seconds: 60

service:
  byggr:
    filter-util:
      applicant:
        roles: SOK

neighborhood-notification-template:
  byggr-files:
    version: '@project.version@'
    sub-directory: /files/

cache:
  enabled: true
  caches:
    - name: getRolesCache
      maximum-size: 100
      expire-after-write: PT24H
    - name: getDocumentCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: findNeighborhoodNotificationsCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: findApplicantErrandsCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: getPropertyDesignationCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: getErrandTypeCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: listNeighborhoodNotificationFilesCache
      maximum-size: 100
      expire-after-write: PT5M
    - name: getHandlingTyperCache
      maximum-size: 250
      expire-after-write: PT24H

logging:
  level:
    root: INFO
logbook:
  body-filters:
    xPath:
        - key: '//filBuffer/text()'
          value: '[binary]'
  logs:
    maxBodySizeToLog: 1000000
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

spring:
  application:
    name: api-service-byggr-integrator
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
