#========================================
# Test profile settings (junit tests)
#========================================
integration:
  byggr:
    url: http://somehost.com
    connect-timeout-in-seconds: 1
    read-timeout-in-seconds: 2
    mapper:
      applicant:
        roles: SOK, KPER

neighborhood-notification-template:
  byggr-files:
    domain: http://somewhere.com/
    sub-directory: /files/
