#========================================
# Test profile settings (junit tests)
#========================================
integration:
  byggr:
    url: http://somehost.com
    connect-timeout-in-seconds: 1
    read-timeout-in-seconds: 2
    cache-ttl: PT24H
service:
  byggr:
    filter-util:
      applicant:
        roles:
          - SOK
          - MSOK
          - KPER
          - OMB
          - KOA
      notifications:
        unwanted-event-types:
          - UNWANTED1
          - UNWANTED2
      document-types:
        unwanted-document-types:
          - GRA
          - REMISS
          - UNDUT
neighborhood-notification-template:
  byggr-files:
    domain: http://somewhere.com/
    sub-directory: /files/
