#========================================
# Test profile settings (IT tests)
#========================================
integration:
  byggr:
    url: http://localhost:${wiremock.server.port}/api-byggr/endpoint
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 30
neighborhood-notification-template:
  byggr-files:
    domain: http://localhost/
    sub-directory: /files/

file-access-token:
  expiration: PT24H
  cron: "-"

cache:
  enabled: false

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///ittest
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate

service:
  byggr:
    filter-util:
      applicant:
        roles:
          - SOK
          - MSOK
          - KPER
          - OMB
          - KOA
      notifications:
        unwanted-event-types:
          - UNWANTED1
          - UNWANTED2
      document-types:
        unwanted-document-types:
          - GRA
          - REMISS
          - UNDUT
