#========================================
# Test profile settings (IT tests)
#========================================
integration:
  byggr:
    url: http://localhost:${wiremock.server.port}/api-byggr/endpoint
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 30
    cache-ttl: PT24H
neighborhood-notification-template:
  byggr-files:
    domain: http://localhost/
    sub-directory: /files/

cache:
  enabled: false

service:
  byggr:
    filter-util:
      applicant:
        roles:
          - SOK
          - MSOK
          - KPER
          - OMB
          - KOA
      notifications:
        unwanted-event-types:
          - UNWANTED1
          - UNWANTED2
      document-types:
        unwanted-document-types:
          - GRA
          - REMISS
          - UNDUT
