#========================================
# General settings
#========================================
integration:
  byggr:
    connect-timeout-in-seconds: 10
    read-timeout-in-seconds: 60
    mapper:
      applicant:
        roles: SOK
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-byggr-integrator
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
