#========================================
# Test profile settings (junit tests)
#========================================
integration:
  byggr:
    url: http://somehost.com
    connect-timeout-in-seconds: 1
    read-timeout-in-seconds: 2
service:
  byggr:
    filter-util:
      applicant:
        roles: SOK, KPER
      notifications:
        unwanted-event-types: UNWANTED1, UNWANTED2

neighborhood-notification-template:
  byggr-files:
    domain: http://somewhere.com/
    sub-directory: /files/
